### ISSUE TITLE
the watch can only catch once?

### ISSUE THREAD

**Issue by zhbhhb** [maragkose/etcd3-client#1]
First of all, thank you for your work.
I make and run the test of watch, but watch can only work once by every key.
Here is the watch log:
```
# ./watcher 
Setup 1st watch
Ctor of AsyncWatcherCall [0x1747ac0]
Write ok and got_tag0x1:1
Adding callback to map with tag: 0x1747ac0
Setup 2nd watch
Ctor of AsyncWatcherCall [0x17428c0]
Write ok and got_tag0x1:1
Adding callback to map with tag: 0x17428c0
Request Read for tag: 0x17428c0
Request Read for tag: 0x1747ac0
Status for received tag [0x1747ac0]: 1
Key1 changed!
Status for received tag [0x17428c0]: 1
Key2 changed!
Status for received tag [0x1747ac0]:1
SomeKey:1
Status for received tag [0x17428c0]:1
OtherKey:4
```

And Here is the operation to change key:
```
# ETCDCTL_API=3 ./etcdctl put SomeKey 1
OK
# ETCDCTL_API=3 ./etcdctl put SomeKey 2
OK
# ETCDCTL_API=3 ./etcdctl put SomeKey 3
OK
# ETCDCTL_API=3 ./etcdctl put OtherKey 4
OK
# ETCDCTL_API=3 ./etcdctl put OtherKey 5
OK
# ETCDCTL_API=3 ./etcdctl put OtherKey 6
OK
```

So, the watch can only  catch operation "put SomeKey 1" and "put OtherKey 4", and miss others, Or the watch can only catch the first operation of every key.

**Comment by maragkose** [comment]
Hi, sorry for the late reply.. Is this from the latest code? I actually commited some in progress work I was doing on the watch so It might not work 100%. I will have a look.
It should catch all put requests.

**Comment by maragkose** [comment]
Hi, 
So it seems the watcher example was the problem..
I committed two watcher examples that do work.

**Comment by zhbhhb** [comment]
OK, the new version that do work fine, Thanks!
